import plugins._000_start
import plugins._000_water_meter_control
import plugins._001_command
import plugins._002_filter_old_message
import plugins._005_drive_mode
import plugins._006_water_meter_filter
import plugins.qq_namelist
import plugins.show_group_id
import plugins.for_fun
import plugins._100_text_forward

