import plugins.qq_namelist
import plugins.show_group_id
import plugins.for_fun
import plugins.alipay_redpack

import plugins._000_water_meter_control
import plugins._001_group_invite

import plugins._1001_command
import plugins._1002_filter_old_message
import plugins._1005_drive_mode
import plugins._1006_water_meter_filter
import plugins._1100_text_forward

