import plugins.qq_namelist
import plugins.show_group_id
import plugins.for_fun
import plugins.alipay_redpack
import plugins.recall

import plugins._002_water_meter_control
import plugins._000_admins
import plugins._001_group_invite

import plugins._1002_command
import plugins._1001_filter_old_message
import plugins._1005_drive_mode
import plugins._1006_water_meter_filter
import plugins._1100_text_forward

import plugins._1101_other_qq_group_events
